name: openwebui
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    networks:
      cloudflared-network: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: ollama
        target: /root/.ollama
        volume: {}
      - type: volume
        source: open-webui
        target: /app/backend/data
        volume: {}
    environment:
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=Cf-Access-Authenticated-User-Email
networks:
  cloudflared-network:
    name: cloudflared-network
    external: true
volumes:
  ollama:
    name: openwebui_ollama
  open-webui:
    name: openwebui_open-webui
